import firebase_admin
from firebase_admin import credentials, firestore, initialize_app
import difflib

# Initialize Firebase
if not firebase_admin._apps:
    cred = credentials.Certificate("firebase_key.json")
    initialize_app(cred)

db = firestore.client()
CITY = "Los Angeles"

# Load known venues manually curated (normalize to lowercase, stripped)
known_venues = [
    "Academy LA",
    "Avalon Hollywood",
    "Bar Lis",
    "Bardot (at Avalon)",
    "Barney's Beanery",
    "Boardner's",
    "Burgundy Room",
    "Cabo Cantina (Hollywood)",
    "Cat & Fiddle",
    "Desert 5 Spot",
    "Dirty Laundry",
    "Dragonfly Hollywood",
    "Elbow Room",
    "Employees Only LA",
    "Frolic Room",
    "Good Times at Davey Wayne's",
    "Grandmaster Recorders",
    "Harriett's Rooftop",
    "Harvard & Stone",
    "Library Bar",
    "pare Room",
    "Hotel Café",
    "Hyde Sunset",
    "Jameson's Irish Pub",
    "Keys Nightclub",
    "La Descarga",
    "La Mesa",
    "Los Globos",
    "Madam Siam",
    "Melrose Umbrella Co.",
    "No Vacancy",
    "PH Day Club",
    "Poppy",
    "Power House",
    "Revolver",
    "Rocco's WeHo",
    "Sassafras Saloon",
    "Scum & Villainy Cantina",
    "Sound",
    "Station Hollywood",
    "Sunset at EDITION",
    "Te'Kila",
    "The Abbey",
    "The Bourbon Room",
    "The Highlight Room",
    "The Nickel Mine",
    "The Roof at EDITION",
    "The Room Hollywood",
    "Tramp Stamp Granny's",
    "W Hollywood - Station 1640",
    "Warwick",
    "1212 Santa Monica",
    "Bar Chloe",
    "Basement Tavern",
    "Big Dean's Ocean Front Cafe",
    "Bodega Wine Bar",
    "Buffalo Club",
    "Busby's West",
    "Cabo Cantina (Santa Monica)",
    "Calabra (Proper Hotel)",
    "Canary",
    "Casa del Mar (Terrazza Lounge)",
    "Chez Jay",
    "Elephante Beach House",
    "Esters Wine Shop & Bar",
    "Father's Office",
    "Harvelle's",
    "Hi Tops",
    "Jameson's Pub",
    "JuneShine",
    "Lanea",
    "Library Alehouse",
    "Mom's Bar",
    "Mother Lode",
    "O'Brien's Irish Pub",
    "Offhand Wine Bar",
    "Rick's Tavern on Main",
    "Rustic Canyon",
    "Rusty's Surf Ranch",
    "Santa Monica Brew Works",
    "Seaside on the Pier",
    "Senator Jones",
    "SHOREBar",
    "Sonny McLean's",
    "Sugar Palm (Viceroy)",
    "Tavern",
    "The Britannia Pub",
    "The Brixton",
    "The Bungalow",
    "The Chestnut Club",
    "The Coco Club",
    "The Craftsman Bar & Kitchen",
    "The Daily Pint",
    "The Galley",
    "The Gaslite",
    "The Georgian Room",
    "The Misfit",
    "The Nickel Mine",
    "The Penthouse",
    "The Room Santa Monica",
    "The Victorian",
    "Trip",
    "West 4th & Jane",
    "Ye Olde King's Head",
    "Baja Cantina",
    "Belles Beach House",
    "Brennan's",
    "El Chucho",
    "High Rooftop Lounge",
    "Hinano Café",
    "Nalu Vida Venice",
    "Ōwa",
    "Roosterfish",
    "Sidewalk Café",
    "The Brig",
    "The Del Monte Speakeasy",
    "The Lincoln",
    "The Little Friend Bar",
    "The Otheroom",
    "The Waterfront",
    "Townhouse & The Del Monte",
    "Venice Ale House",
    "Venice Beach Bar",
    "Venice Whaler",
    "Winston House",
    "Broxton Brewery & Pub",
    "Firefly",
    "Habibi Café",
    "Living Room Bar at W Hotel",
    "Neat",
    "Q's Billiard Club (adjacent)",
    "Rocco's Tavern",
    "Skylight Gardens",
    "STK Los Angeles (Westwood)",
    "The Tuck Room",
    "Wolfsglen",
    "33 Taps DTLA",
    "901 Bar & Grill",
    "Apothéke LA",
    "Arts District Brewing",
    "Bacari West Adams",
    "Broken Shaker",
    "Clifton's Republic",
    "Exchange LA",
    "Golden Gopher",
    "La Barca Restaurant",
    "La Chupería (“The Miche Spot”)",
    "Library Bar",
    "Pattern Bar",
    "Perch",
    "Potions & Poisons",
    "Prank Bar",
    "Rock & Reilly's USC Village",
    "Seven Grand",
    "Sinners y Santos",
    "The Belasco",
    "The Continental Club",
    "The Edison",
    "The Mayan",
    "The Reserve",
    "The Rooftop at The Wayfarer",
    "The Short Stop",
    "The Wolves",
    "Tirebiter Brewery",
    "APT 503",
    "Arena Ktown",
    "Bamboo House",
    "Beer Belly",
    "Biergarten LA",
    "Break Room 86",
    "Burlington Room",
    "Cafe Brass Monkey",
    "Dan Sung Sa",
    "Dwit Gol Mok",
    "Escala",
    "Frank 'n Hank",
    "Gaam Karaoke",
    "Intercrew",
    "Kiss Kiss Bang Bang",
    "LAces",
    "Lock & Key",
    "Mama Lion",
    "Nine O Five (905 Bar)",
    "Palm Tree Karaoke",
    "Paper Tiger Bar",
    "Pharaoh Karaoke Lounge",
    "R Bar",
    "Rosen Karaoke",
    "SoopSok Karaoke",
    "Southland Beer",
    "Terra Cotta",
    "The HMS Bounty",
    "The Normandie Club",
    "The Prince",
    "The Venue",
    "Toe Bang Cafe",
]
known_normalized = {name.strip().lower() for name in known_venues}

# Fetch all venues in Firestore
print("\n🔍 Comparing Firestore venues against known list...")
venues_ref = db.collection("cities").document(CITY).collection("venues")
firestore_docs = list(venues_ref.stream())

existing_names = set()
for doc in firestore_docs:
    data = doc.to_dict()
    name = data.get("name", "").strip().lower()
    if name:
        existing_names.add(name)

# Find known venues missing from Firestore
missing = []
for known in known_normalized:
    if known not in existing_names:
        close_matches = difflib.get_close_matches(known, existing_names, n=2, cutoff=0.85)
        if not close_matches:
            missing.append(known)

# Print summary
print(f"\n⚠️  {len(missing)} known venues are missing from Firestore:")
for name in sorted(missing):
    print(f"  - {name}")

print("\n✅ Comparison complete.")
